# fly.toml app configuration file generated for planpal-redis on 2025-11-16T21:48:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'planpal-redis'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[env]
  REDIS_ARGS = "--save 60 1 --appendonly yes"

[[services]]
  protocol = 'tcp'
  internal_port = 6379
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 6379

[[vm]]
  size = 'shared-cpu-1x'
